# 基础配置
Base:
  # web 服务端口
  WebPort: "9292"
  # 回调地址
  CallbackURL: ""

# 日志配置
Logger:
  # 日志存放路径，当前目录的log文件夹
  Path: "/tmp"
  # 日志打印等级，[debug, info, warn, err, off]
  Level: "debug"
  # 最大存放时间，7天，超过7天的日志会删除
  MaxAge: 7
  # 日志分割时间，24小时，日志以1天为单位分割，一天一个文件
  RotationTime: 24
  # 是否启用控制台输出
  StdOut: true

# 数据仓库配置
Repo:
  # mysql连接
  Connection: "root:123456@tcp(127.0.0.1:3306)/expire?charset=utf8&parseTime=True&loc=Local"

# redis连接
Redis:
  Connection: 127.0.0.1:6379
  Username: ""
  Password: ""

# 消息推送配置
Message:
  Connection: ""
  Icon: https://day.app/assets/images/avatar.jpg
  Title: "您有新的消息"